### ISSUE TITLE
Your theme is listed on jekyll-themes.com

### ISSUE THREAD

**Issue by sharu725** [ramswaroop/photography#1]
Your theme has been listed on [https://jekyll-themes.com/](https://jekyll-themes.com/).

**Comment by ramswaroop** [comment]
@sharu725 Btw how did you find this repo of mine?

**Comment by sharu725** [comment]
@ramswaroop, you added a topic `jekyll-themes` in your repo. I was searching for new themes in Github.

**Comment by ramswaroop** [comment]
@sharu725 Cool! So, the topics are of good use then :)

**Comment by sharu725** [comment]
I never knew. Tried it yesterday. They are like hashtags I believe.
