### ISSUE TITLE
Hard coded author name

### ISSUE THREAD

**Issue by J3soon** [ramswaroop/photography#12]
There are hard coded author names in `index.html`'s line 10 and line 38.

    <h1><a href="index.html"><strong>Photography</strong> by Ram Patra</a></h1>

    <h2>Hey there, my name is Ram</h2>

I'm wondering that maybe those 2 places should use `{{ site.title }}` and `{{ site.author }}`

**Comment by J3soon** [comment]
Oh, there's already a pull request #10 .

**Comment by ramswaroop** [comment]
Yes, I will be reviewing the PR tonight. This PR has been lying around for many days now.

**Comment by J3soon** [comment]
OK, thanks. 👍

**Comment by ramswaroop** [comment]
PR merged!
