### ISSUE TITLE
Change order of pictures - sort pictures

### ISSUE THREAD

**Issue by mattmusc** [ramswaroop/photography#15]
Is it possibile to change order of the pictures displayed?
Now I think pictures are sorted by name in alphabetical order right?

**Comment by ramswaroop** [comment]
Yes, it's arranged chronologically by default. But you can sort the pictures the way you want. You just need to modify `index.html`. See a [simple sorting example in jekyll](https://gist.github.com/lukecathie/2b4eaad90467b3a7c266).

**Comment by mattmusc** [comment]
Thanks, for me this issue can be closed.

**Comment by palermog** [comment]
I'm interested in sorting by EXIF data — especially by the original date captured, rather than date uploaded to Github. Is there a way to make the EXIF available as a sort parameter in liquid, maybe by export? Then I could imagine making different pages that filter by keyword.
