### ISSUE TITLE
No thumbnail

### ISSUE THREAD

**Issue by neiram44** [ramswaroop/photography#2]
Hej,

I'm giving a try to your fantastic theme. I have one issue.

The thumbnails are not appearing properly it's just a black square. If I click on it it shows perfectly the full size image.

Any tips around what I may have done wrongly??

Thanks

**Comment by ramswaroop** [comment]
Hey,

Seeing your repo it seems the image extension `.JPG` doesn't seem to work. Please change all image extensions to `.jpg` in your `images/thumbs` folder. It should work after that. Thanks for reporting, will make it case insensitive.

**Comment by ramswaroop** [comment]
Hey,

Looking at the code it seems the case doesn't matter. The problem in your case was that the images inside `fulls` had `.jpg` extension and inside `thumbs` had `.JPG`. Both should have an exactly same name and extension to make it work.

**Comment by neiram44** [comment]
Thanks, it's working even if I still didn't catch the exact root cause. Thanks for your work.

**Comment by ramswaroop** [comment]
The root cause is that the images inside `fulls` and `thumbs` directory should have the exact same names (including extensions) and same case.
