### ISSUE TITLE
Not seeing images locally

### ISSUE THREAD

**Issue by geografa** [ramswaroop/photography#3]
I'm running `jekyll serve --watch` but still unable to see thumbs and images locally. The built site shows empty images and links. I've run gulp and everything seems to work:

```
[15:15:54] Using gulpfile ~/htdocs/photography/gulpfile.js
[15:15:54] Starting 'resize'...
[15:15:54] Finished 'resize' after 17 ms
[15:15:54] Starting 'del'...
[15:15:54] Finished 'del' after 5.31 ms
[15:15:54] Starting 'default'...
[15:15:54] Finished 'default' after 33 μs
```

The site and images load on the live site but I can't get it to run locally. I'm running `jekyll 3.1.6`

**Comment by ramswaroop** [comment]
Hi @geografa, can you please push your code changes to your github repo so that I can look at the issue?

**Comment by geografa** [comment]
@ramswaroop thanks for looking :) Changes are in the `gh-pages` branch: https://github.com/geografa/photography/tree/gh-pages

**Comment by ramswaroop** [comment]
Hi, I found the issue. Your image `aDSC_0938.jpg` is there in `fulls` directory but not in `thumbs`. Please put a (smaller version of the image for faster loading) of the image and your image will start appearing.

**Comment by geografa** [comment]
@ramswaroop I thought gulp did this. Should this be a manual process?

**Comment by geografa** [comment]
rebuilt with latest Jekyll and bundle installed again. Everything looks good 👍 . Thanks for making a great template!

**Comment by ramswaroop** [comment]
@geografa Yes, `$ gulp` command compresses all the images in `/images` directory to `/fulls` and `/thumbs` directories automatically. It should work okay as it works at my end and no one else has raised any issue yet. 

I think there is no issue in jekyll as the images weren't there in the directory itself so how will jekyll display them. Just make sure after running `$ gulp` you have the images in the respective directories.
